title: Exploring GIS
logo: /assets/img/logo.JPG
description: This is my personal website where I share my thoughts and opinions on all things GIS. All views are mine.
show_downloads: false
exclude:
- README.md
google_analytics:
theme: jekyll-theme-minimal