title: Moussa Dia
logo: /assets/img/logo.JPG
description: This is my personal blog where I share my thoughts and opinions on all things GIS.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal