theme: jekyll-theme-minimal
title: Exploring GIS
description: This is my personal blog where I share my thoughts and opinions on all things GIS.
logo: C:\Users\mwdia\Documents\GitHub\images\logo.JPG
show_downloads: false